### ISSUE TITLE
hello，Is there any other way to get processed data?

### ISSUE THREAD

**Issue by bruce-xie** [JJN123/Fall-Detection#2]
I have already contacted Dr. Khan by email. Maybe my mail is classified as spam. Can you still provide other ways to get processed data?

Sincerely,

**Comment by titubeta** [comment]
The best way to contact is to use university email ids, or standard email addresses (e.g. gmail). Do not use strange email domains that may be caught as spam (e.g. 163.com). If I notice a request on my Spam folder, I try to respond back.
The data is large and stored on an institutional encrypted drive, so it is not available to download from other source.
