### ISSUE TITLE
Is 3D convolutional autoencoder model code correct?

### ISSUE THREAD

**Issue by droiter** [JJN123/Fall-Detection#5]
How come DSTCAE_C3D model replaced by dummy_3d?

        model, model_name, model_type = DSTCAE_C3D(img_width, img_height, win_len)
        model, model_name, model_type = dummy_3d(img_width, img_height, win_len)  --?

**Comment by JJN123** [comment]
You are right, the second line was for debugging, and should be removed; I will make this change.
