### ISSUE TITLE
Hello, I have two questions, can you answer it?

### ISSUE THREAD

**Issue by mstc-xqp** [JJN123/Fall-Detection#6]
![41e156516cbab80b40b57f046fac37e](https://user-images.githubusercontent.com/19384581/77630319-c97d7f80-6f85-11ea-84ef-f1fda9138f01.png)
Why can't I load the dataset
![1976a283de0ba24c2ff5214ecd71fe2](https://user-images.githubusercontent.com/19384581/77630346-d13d2400-6f85-11ea-84d6-9fd33c20f1cc.png)

**Comment by titubeta** [comment]
From the first message, it appears that your ADL and Fall folders may be empty. Please make sure you have the required images in these folders.

**Comment by mstc-xqp** [comment]
> From the first message, it appears that your ADL and Fall folders may be empty. Please make sure you have the required images in these folders.
I fix it and comes the problem as shows in  the second message.
I had place the required images in these folders
![image](https://user-images.githubusercontent.com/19384581/77892718-a1539080-72a5-11ea-8730-f5318dc8865e.png)

![image](https://user-images.githubusercontent.com/19384581/77892243-e2977080-72a4-11ea-9ea4-d68a2e4c7404.png)


should I ask you for the data?
![769acd6b7b5b1f1cd8b7c27100c3a18](https://user-images.githubusercontent.com/19384581/77893298-5423ee80-72a6-11ea-9680-d964e1abd7c1.png)

**Comment by titubeta** [comment]
If you have images in the folders, you should not get the problem. If you do not have fall data with you, the please request it (as per the instructions) and I will give you access to it.

**Comment by mstc-xqp** [comment]
> If you have images in the folders, you should not get the problem. If you do not have fall data with you, the please request it (as per the instructions) and I will give you access to it.


I use the original data which is already in the git package. but only have two


 
![image](https://user-images.githubusercontent.com/19384581/77940016-996a0f80-72ea-11ea-9741-26852b36387f.png)

![image](https://user-images.githubusercontent.com/19384581/77939954-83f4e580-72ea-11ea-9b56-6238a97988ae.png)

**Comment by titubeta** [comment]
Make sure the folder name is correctly given as discussed here - https://github.com/JJN123/Fall-Detection/tree/master/Fall-Data

**Comment by mstc-xqp** [comment]
yeah i am sure i follow this instruction.



---Original---

**Comment by titubeta** [comment]
As per instructions if you have set
dset == 'Thermal-dummy':
    path_Fall = '/Thermal-dummy/Fall/Fall*'
    path_ADL =  '/Thermal-dummy/NonFall/ADL*'
then, it should work. Otherwise, it is not clear to me, why it will not.

**Comment by mstc-xqp** [comment]
> As per instructions if you have set
> dset == 'Thermal-Dummy':
> path_Fall = '/Thermal-Dummy/Fall/Fall*'
> path_ADL = '/Thermal-Dummy/NonFall/ADL*'
> then, it should work. Otherwise, it is not clear to me, why it will not.


Thank you very much.But it comes new problems.
![142bd4567d3d27dbb80076c2b9aa919](https://user-images.githubusercontent.com/19384581/77987325-1d081880-734c-11ea-9e5a-9c82ae38a145.png)

**Comment by mstc-xqp** [comment]
> As per instructions if you have set
> dset == 'Thermal-Dummy':
> path_Fall = '/Thermal-Dummy/Fall/Fall*'
> path_ADL = '/Thermal-Dummy/NonFall/ADL*'
> then, it should work. Otherwise, it is not clear to me, why it will not.
Thank you very much. But it comes the new problems. 
![80c6456402666d4719b210ed8b7ac65](https://user-images.githubusercontent.com/19384581/77987708-1e861080-734d-11ea-977b-7fa3c6f2e544.png)


And if i want to To generate an animation, such as shown in the above GIF,

run dae_main_test.py, with animate option set to True.

But where is the  " animate option"

**Comment by titubeta** [comment]
We cannot provide support for programming issues. I would suggest you to please fix them for yourself. Thanks for your understanding.

**Comment by mstc-xqp** [comment]
> We cannot provide support for programming issues. I would suggest you to please fix them for yourself. Thanks for your understanding.
Thank you !!!

And if i want to To generate an animation, such as shown in the above GIF,

run dae_main_test.py, with animate option set to True.

But where is the " animate option"

**Comment by titubeta** [comment]
Line 23: dae_exp.test(raw = False, **animate** = False)
Please read the code carefully. We cannot fix your programming issues. Thanks for understanding.
